name: WorkflowBasics
on: workflow_dispatch
env:
  workflow-level: UnlimitedScope
  website: spotify.com

jobs:
  print-some-stuff:
    runs-on: ubuntu-latest
    env:
      job-level: warrior

  strategy:
    matrix:
      heroes: [Knife, Axe, Wand]
      name: [Thief, Warrior, Wizard]
    steps:
      - name: setup another env var
        env:
          secret: 42
        run: |
          echo "with gh expression syntax {{ env.secret}}"
          echo "with pure bash $secret"

      - name: print some stuff
        env:
          this-step: wizard
        run: |
          echo "Hello World from the wizard in the workflow"
          echo "Our env is: ${{ toJson(env)}}"
          echo "Our vars is: ${{ toJson(vars)}}"

      - name: matrix time
        run: |
          echo "Our matrix is: ${{ toJson(matrix) }}"
          echo "${{ matrix.name}}s belongs to ${{ matrix.heroes}}"
